CREATE TABLE IF NOT EXISTS ACCOUNT (
  id IDENTITY,
  balance DECIMAL(19,4) NOT NULL,
  version INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS OPERATION (
  id IDENTITY,
  from_id int NOT NULL,
  to_id int NOT NULL,
  amount DECIMAL(19,4) NOT NULL,
  time TIMESTAMP,

  FOREIGN KEY (from_id) REFERENCES ACCOUNT (id),
  FOREIGN KEY (to_id) REFERENCES ACCOUNT (id)
);
